import { Roboto } from "next/font/google";
import "./globals.css";
import BoardGuruContext from "@/context/BoardGuruContext";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Board Guru",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <BoardGuruContext>{children}</BoardGuruContext>
      </body>
    </html>
  );
}
